# Generated by Django 4.2.14 on 2024-08-27 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="address",
            name="zip",
            field=models.IntegerField(),
        ),
    ]
