# Generated by Django 4.2.14 on 2024-09-25 07:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="count",
        ),
    ]
