# Generated by Django 5.1 on 2024-08-26 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="default",
            field=models.BooleanField(default=False),
        ),
    ]
