# Generated by Django 5.1 on 2024-08-19 23:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_user_password_reset_at"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="password_reset_at",
            new_name="password_changed_at",
        ),
    ]
