# Generated by Django 4.2.14 on 2024-09-23 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_remove_profile_address"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="settled_status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("delivered", "Delivered"),
                    ("cancelled", "Cancelled"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
    ]
