# Generated by Django 4.2.14 on 2024-09-17 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_discount"),
    ]

    operations = [
        migrations.AlterField(
            model_name="discount",
            name="discount_percentage",
            field=models.FloatField(),
        ),
    ]
