# Generated by Django 5.1 on 2024-09-08 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_supplier_product_supplier"),
    ]

    operations = [
        migrations.AlterField(
            model_name="review",
            name="rating",
            field=models.FloatField(),
        ),
    ]
