# Generated by Django 5.1 on 2024-09-23 18:20

import api.validators.product
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_store_inventory"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="image",
            field=models.ImageField(
                upload_to="api/images/",
                validators=[api.validators.product.validate_file_size],
            ),
        ),
    ]
