# Generated by Django 5.1 on 2024-08-26 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_payment_default"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="otp_code",
            field=models.CharField(max_length=6, null=True),
        ),
    ]
