# Generated by Django 5.1 on 2024-09-22 17:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_variant_variantoption_productvariant"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="productvariant",
            name="sku",
        ),
        migrations.AlterField(
            model_name="productvariant",
            name="price",
            field=models.FloatField(
                validators=[django.core.validators.MinValueValidator(0)]
            ),
        ),
    ]
